# Generated by Django 3.2.18 on 2023-04-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0024_campaign_default_fundraiser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photo',
            field=models.ImageField(blank=True, upload_to='campaignphotos/'),
        ),
    ]
