# Generated by Django 3.2.18 on 2023-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0025_campaign_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='campaignphotos/'),
        ),
    ]
