# Generated by Django 3.2.18 on 2023-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0026_campaign_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='signup_email_closing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='signup_email_opening',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='signup_email_subject',
            field=models.TextField(blank=True),
        ),
    ]
