# Generated by Django 3.2.18 on 2024-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0029_auto_20230419_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='business_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='business_logo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
