# Generated by Django 3.2.18 on 2024-03-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0030_add_business_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='website_url',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='business_logo',
            field=models.ImageField(blank=True, upload_to='donationphotos/'),
        ),
    ]
